"""3rd init

Revision ID: adf4d5b45899
Revises: 8f11ce7dbccc
Create Date: 2023-06-10 20:17:42.706312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf4d5b45899'
down_revision = '8f11ce7dbccc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
